### ISSUE TITLE
All notes are broken?

### ISSUE THREAD

**Issue by christiaangoossens** [nikitavoloboev/awesome-tue-software#1]
All links to infinit.io for slides, notes etc. present a "Missing FIle",  "There doesn't seem to be any files here." error. Could you fix the links?

Thanks for sharing your resources!  👍

**Comment by nikitavoloboev** [comment]
Yeah, will update the links shortly. Sadly Infinit closed down but I will reupload them and update the repo. 

Glad you find it useful. 🙂

**Comment by nikitavoloboev** [comment]
I updated the links. 🙂
